
CFLAGS+= -D__PLATFORM_WIN32__ -g -fno-strict-aliasing -D__WINDOWS_DS__
LDFLAGS+= -lstdc++ -ldl -lm  -g -ldinput -ldsound -ldxguid -luser32 -lws2_32 -lwinmm -lole32
CSRCS+= util_sndfile.c

CXXSRCS -= ulib_regex.cpp